version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.5
    container_name: lamp_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - lamp_network

  # Memcached - localhost only access
  memcached:
    image: memcached:1.4-alpine
    container_name: lamp_memcached
    restart: unless-stopped
    ports:
      - "127.0.0.1:11211:11211"
    command: sh -c "memcached -m 64 -l 0.0.0.0 -p 11211 -u memcache -U 0"
    networks:
      - lamp_network

  # Apache + PHP 5.6 Official Docker Image
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lamp_web
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./www:/var/www/html
      - ./config/apache:/etc/httpd/conf.d
      - ./config/php:/etc/php.d
      - ./logs/apache:/var/log/httpd
      - ./ssl:/etc/ssl/certs
    depends_on:
      - mariadb
      - memcached
    environment:
      - DB_HOST=mariadb
      - DB_NAME=webapp
      - DB_USER=webuser
      - DB_PASS=webpassword
      - MEMCACHED_HOST=memcached
    networks:
      - lamp_network

volumes:
  mariadb_data:

networks:
  lamp_network:
    driver: bridge